version: '3'

services:

  db:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}

    ports:
      - 127.0.0.1:${LOCAL_DB_PORT}:5432

  app:
    restart: always
    build: .
    environment:
      DEBUG: 'false'
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    ports:
      - 127.0.0.1:${LOCAL_API_PORT}:8000
    command: poetry run python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  db_data:
  app:
